# .streamlit/secrets.toml

# 1. The full JSON contents of your service-account key:
[GSHEET_KEY]
type                    = "service_account"
project_id              = "my-gcp-project"
private_key_id          = "XXXX"
private_key             = '''-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqh…(your key)…QIDAQAB
-----END PRIVATE KEY-----'''
client_email            = "streamlit-sa@my-gcp-project.iam.gserviceaccount.com"
client_id               = "1234567890"
auth_uri                = "https://accounts.google.com/o/oauth2/auth"
token_uri               = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url    = "https://www.googleapis.com/.../certs"

# 2. The names of the two worksheets within that Google Sheet:
RESPONSES_SHEET_NAME = "Responses"
GAME_SHEET_NAME      = "Game"
